version: '3'
services:
  api:
    build: ./api
    container_name: go-api-container
    ports:
      - "8100:8080"  # Expose port 8080 inside the container as port 8100 on the host
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=testdb
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: go-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local